"""サンプル用のテーブル

Revision ID: a682e55e8251
Revises: 
Create Date: 2021-05-18 16:28:02.046667

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a682e55e8251'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    sample_table = op.create_table('sample',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(sample_table, [
        {"name": "hello world"}
    ])

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample')
    # ### end Alembic commands ###
